version: '3.5'

services:

  airport-sim-client:
    build:
      context: ./AirportSim.Client/ClientApp
      dockerfile: ./Dockerfile
    container_name: airport-sim-client
    restart: always
    ports:  
      - "4200:80"
    depends_on: 
      - airport-sim-simulator
    networks:
      - airportsim_network

  airport-sim-control-tower:
    build:
      context: ./AirportSim
      dockerfile: ./Dockerfile
    container_name: airport-sim-control-tower
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      SQL_SERVER: Server=airportsim-mssql;Database=AirportSim.db;User=sa;Password=Pa55!W0rd
      SIGNALR_CLIENT: http://localhost:4200
      SIMULATOR_CLIENT: http://airport-sim-simulator
    ports:
      - "5050:80"
    depends_on: 
      - airportsim-mssql
    networks:
      - airportsim_network

  airport-sim-simulator:
    build:
      context: ./AirportSim.Simulator
      dockerfile: ./Dockerfile
    container_name: airport-sim-simulator
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      CLIENT_URL: http://localhost:4200
      AIRPORTSIM_URL: http://airport-sim-control-tower
    ports:
      - "5000:80"
    depends_on: 
      - airport-sim-control-tower
    networks:
      - airportsim_network

  airportsim-mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: airportsim-mssql
    volumes: 
      - airportsim_mssql_volume:/var/opt/mssql
    restart: always
    environment:
      SA_PASSWORD: Pa55!W0rd
      ACCEPT_EULA: Y
    networks:
      - airportsim_network

networks: 
  airportsim_network:
    driver: bridge

volumes: 
  airportsim_mssql_volume: {}
